#!/usr/bin/env python3
"""Render the measured-claim SVGs embedded in the E8450 ROM handbook.

No third-party packages are required. Data is intentionally kept beside its
chart definition so reviewers can compare every plotted value with the cited
source. Run with --check to fail when committed SVGs are stale.
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "assets"

INK = "#172033"
MUTED = "#5f6b7a"
GRID = "#d9e1ea"
PANEL = "#ffffff"
PAGE = "#f4f7fb"
BLUE = "#2878b5"
TEAL = "#159a8c"
ORANGE = "#e07a2d"
RED = "#c84a4a"
PURPLE = "#7957b8"
GREEN = "#4a9b55"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


class SVG:
    def __init__(self, title: str, description: str, height: int = 560):
        self.width = 1000
        self.height = height
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.width} {height}" role="img" aria-labelledby="title desc">',
            f"<title id=\"title\">{esc(title)}</title>",
            f"<desc id=\"desc\">{esc(description)}</desc>",
            '<metadata>Generated by scripts/docs/render-claim-graphs.py</metadata>',
            f'<rect width="1000" height="{height}" rx="18" fill="{PAGE}"/>',
        ]
        self.text(40, 42, title, "title")
        self.text(40, 67, description, "subtitle")

    def text(self, x: float, y: float, value: object, cls: str = "label", anchor: str = "start") -> None:
        styles = {
            "title": (25, 700, INK),
            "subtitle": (14, 400, MUTED),
            "panel-title": (17, 700, INK),
            "label": (14, 400, INK),
            "small": (12, 400, MUTED),
            "value": (14, 700, INK),
        }
        size, weight, fill = styles[cls]
        self.parts.append(
            f'<text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" '
            f'font-family="sans-serif" font-size="{size}" font-weight="{weight}" '
            f'fill="{fill}">{esc(value)}</text>'
        )

    def line(self, x1: float, y1: float, x2: float, y2: float, cls: str = "axis", **attrs: object) -> None:
        stroke = attrs.pop("stroke", GRID if cls == "grid" else "#8d99a8")
        stroke_width = attrs.pop("stroke_width", 1)
        extra = " ".join(f'{k.replace("_", "-")}="{esc(v)}"' for k, v in attrs.items())
        self.parts.append(
            f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
            f'stroke="{stroke}" stroke-width="{stroke_width}" {extra}/>'
        )

    def rect(self, x: float, y: float, w: float, h: float, fill: str, rx: float = 0, **attrs: object) -> None:
        extra = " ".join(f'{k.replace("_", "-")}="{esc(v)}"' for k, v in attrs.items())
        self.parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="{rx}" fill="{fill}" {extra}/>'
        )

    def circle(self, x: float, y: float, r: float, fill: str, **attrs: object) -> None:
        extra = " ".join(f'{k.replace("_", "-")}="{esc(v)}"' for k, v in attrs.items())
        self.parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" fill="{fill}" {extra}/>')

    def panel(self, x: float, y: float, w: float, h: float, title: str) -> None:
        self.rect(x, y, w, h, PANEL, 12, stroke=GRID)
        self.text(x + 20, y + 29, title, "panel-title")

    def finish(self, source: str, note: str | None = None) -> str:
        if note:
            self.text(40, self.height - 38, note, "small")
        self.text(40, self.height - 17, f"Source: {source}", "small")
        self.parts.append("</svg>\n")
        return "\n".join(self.parts)


def vertical_bars(
    svg: SVG,
    x: float,
    y: float,
    w: float,
    h: float,
    labels: list[str],
    values: list[float],
    max_value: float,
    colors: list[str],
    suffix: str,
    ticks: int = 4,
    decimals: int = 1,
) -> None:
    plot_left, plot_right = x + 58, x + w - 18
    plot_top, plot_bottom = y + 50, y + h - 58
    plot_h = plot_bottom - plot_top
    for i in range(ticks + 1):
        value = max_value * i / ticks
        gy = plot_bottom - plot_h * i / ticks
        svg.line(plot_left, gy, plot_right, gy, "grid")
        svg.text(plot_left - 8, gy + 4, f"{value:g}", "small", "end")
    svg.line(plot_left, plot_top, plot_left, plot_bottom)
    svg.line(plot_left, plot_bottom, plot_right, plot_bottom)
    slot = (plot_right - plot_left) / len(values)
    bar_w = min(82, slot * 0.52)
    for i, (label, value, color) in enumerate(zip(labels, values, colors)):
        bx = plot_left + slot * (i + 0.5) - bar_w / 2
        bh = plot_h * value / max_value
        by = plot_bottom - bh
        svg.rect(bx, by, bar_w, bh, color, 5)
        shown = f"{value:.{decimals}f}{suffix}"
        svg.text(bx + bar_w / 2, by - 8, shown, "value", "middle")
        svg.text(bx + bar_w / 2, plot_bottom + 23, label, "small", "middle")


def error_bars(
    svg: SVG,
    x: float,
    y: float,
    w: float,
    h: float,
    labels: list[str],
    means: list[float],
    errors: list[float],
    max_value: float,
    colors: list[str],
    suffix: str,
    decimals: int = 1,
) -> None:
    plot_left, plot_right = x + 48, x + w - 16
    plot_top, plot_bottom = y + 50, y + h - 55
    plot_h = plot_bottom - plot_top
    for i in range(5):
        value = max_value * i / 4
        gy = plot_bottom - plot_h * i / 4
        svg.line(plot_left, gy, plot_right, gy, "grid")
        svg.text(plot_left - 7, gy + 4, f"{value:g}", "small", "end")
    slot = (plot_right - plot_left) / len(means)
    bar_w = min(62, slot * 0.44)
    for i, (label, mean, error, color) in enumerate(zip(labels, means, errors, colors)):
        cx = plot_left + slot * (i + 0.5)
        bh = plot_h * mean / max_value
        svg.rect(cx - bar_w / 2, plot_bottom - bh, bar_w, bh, color, 5)
        high = plot_bottom - plot_h * min(max_value, mean + error) / max_value
        low = plot_bottom - plot_h * max(0, mean - error) / max_value
        svg.line(cx, high, cx, low, "axis", stroke_width=2)
        svg.line(cx - 8, high, cx + 8, high, "axis", stroke_width=2)
        svg.line(cx - 8, low, cx + 8, low, "axis", stroke_width=2)
        svg.text(cx, high - 8, f"{mean:.{decimals}f}±{error:.{decimals}f}{suffix}", "value", "middle")
        svg.text(cx, plot_bottom + 22, label, "small", "middle")


def aqm_latency() -> str:
    svg = SVG(
        "AQM cuts loaded latency while preserving upload rate",
        "Same controlled saturating-upload comparison; exact values from the original A/B.",
    )
    svg.panel(35, 92, 450, 390, "Ping p95 under load (lower is better)")
    vertical_bars(svg, 35, 92, 450, 390, ["AQM off", "AQM on"], [196, 33.8], 210, [RED, TEAL], " ms")
    svg.panel(515, 92, 450, 390, "Upload throughput (higher is better)")
    vertical_bars(svg, 515, 92, 450, 390, ["AQM off", "AQM on"], [8.304, 8.178], 9, [BLUE, TEAL], " Mbit/s", decimals=3)
    return svg.finish(
        "docs/research/qos-aqm-lab-notes.md §22.12",
        "One run per mode in this initial gate; later hardened-AQM testing measured 30.5 ms p95.",
    )


def napi_ab() -> str:
    svg = SVG(
        "NAPI weight 256: throughput gain without a p95 regression",
        "Three repeated saturating-load runs per side in the same session.",
    )
    svg.panel(35, 92, 450, 390, "Mean sent rate (higher is better)")
    vertical_bars(svg, 35, 92, 450, 390, ["Weight 64", "Weight 256"], [3.29, 4.47], 5, [BLUE, TEAL], " Mbit/s", decimals=2)
    svg.panel(515, 92, 450, 390, "Ping p95 (lower is better)")
    vertical_bars(svg, 515, 92, 450, 390, ["Weight 64", "Weight 256"], [48.0, 45.3], 55, [BLUE, TEAL], " ms")
    return svg.finish(
        "docs/README.md NAPI measurement table (original A/B retained in git history)",
        "n=3 per side; identical 0.35% loss. Baseline p99/max included one unrelated real-traffic outlier.",
    )


def grace_tuning() -> str:
    svg = SVG(
        "AQM grace-period tuning",
        "poll_ms=100 fixed; three saturating-upload repetitions per grace value.",
        600,
    )
    svg.panel(35, 92, 930, 425, "Latency distribution (lower is better)")
    plot_left, plot_right = 110, 935
    plot_top, plot_bottom = 155, 435
    max_value = 45
    for i in range(6):
        value = max_value * i / 5
        gy = plot_bottom - (plot_bottom - plot_top) * i / 5
        svg.line(plot_left, gy, plot_right, gy, "grid")
        svg.text(plot_left - 10, gy + 4, f"{value:g}", "small", "end")
    groups = [
        ("1000 ms", [30.5, 31.8, 37.1], 0),
        ("3000 ms", [31.7, 36.5, 41.5], 2),
        ("5000 ms", [30.9, 34.7, 36.5], 2),
    ]
    colors = [BLUE, ORANGE, PURPLE]
    metric_names = ["p95", "p99", "max"]
    group_slot = (plot_right - plot_left) / len(groups)
    bar_w = 42
    for gi, (label, values, loss_reps) in enumerate(groups):
        center = plot_left + group_slot * (gi + 0.5)
        for mi, (value, color) in enumerate(zip(values, colors)):
            bx = center + (mi - 1) * (bar_w + 7) - bar_w / 2
            bh = (plot_bottom - plot_top) * value / max_value
            svg.rect(bx, plot_bottom - bh, bar_w, bh, color, 4)
            svg.text(bx + bar_w / 2, plot_bottom - bh - 7, f"{value:.1f}", "small", "middle")
        svg.text(center, plot_bottom + 23, label, "label", "middle")
        svg.text(center, plot_bottom + 43, f"loss in {loss_reps}/3 reps", "small", "middle")
    for i, (name, color) in enumerate(zip(metric_names, colors)):
        lx = 330 + i * 145
        svg.rect(lx, 494, 14, 14, color, 2)
        svg.text(lx + 21, 506, name, "small")
    return svg.finish(
        "docs/research/qos-aqm-lab-notes.md §35.2",
        "Live household traffic makes this a small, noisy n=3 tuning result—not a universal timer benchmark.",
    )


def hold_ab() -> str:
    svg = SVG(
        "AQM hold_ms=3000 production A/B",
        "Four-stream saturation; means ± sample standard deviation.",
        610,
    )
    panels = [
        (35, "Sent rate (Mbit/s)", [8.6, 9.0], [0.7, 0.4], 10.5, "", 1),
        (355, "Ping p99", [39.9, 37.8], [6.0, 5.3], 52, " ms", 1),
        (675, "Retransmits", [1680, 1655], [221, 220], 2100, "", 0),
    ]
    for x, title, means, errors, maximum, suffix, decimals in panels:
        svg.panel(x, 92, 290, 430, title)
        error_bars(svg, x, 92, 290, 430, ["hold 0", "hold 3000"], means, errors, maximum, [BLUE, TEAL], suffix, decimals)
    return svg.finish(
        "docs/README.md AQM hold measurement table (original run log retained in git history)",
        "hold=0 aggregate excludes one severe household-traffic outlier (n=7); hold=3000 uses all eight reps.",
    )


def autorate_ceiling() -> str:
    svg = SVG(
        "Autorate ceiling bug and corrected bound",
        "Rate-controller setting compared with measured sustained download range.",
        570,
    )
    svg.panel(35, 92, 930, 390, "Mbit/s")
    left, right = 235, 925
    top = 160
    rows = [
        ("Pre-fix shaper high", 69.5, RED),
        ("Configured ceiling", 10.0, BLUE),
        ("Post-fix shaper high", 10.0, TEAL),
    ]
    for tick in range(0, 81, 10):
        x = left + (right - left) * tick / 80
        svg.line(x, 145, x, 410, "grid")
        svg.text(x, 435, tick, "small", "middle")
    for i, (label, value, color) in enumerate(rows):
        y = top + i * 78
        svg.text(left - 15, y + 5, label, "label", "end")
        width = (right - left) * value / 80
        svg.rect(left, y - 15, width, 30, color, 5)
        svg.text(left + width + 10, y + 5, f"{value:.1f}", "value")
    range_y = top + 3 * 78
    lo, hi = 6.19, 10.56
    lo_x = left + (right - left) * lo / 80
    hi_x = left + (right - left) * hi / 80
    svg.text(left - 15, range_y + 5, "Measured downloads", "label", "end")
    svg.line(lo_x, range_y, hi_x, range_y, "axis", stroke_width=8, stroke=ORANGE)
    svg.circle(lo_x, range_y, 7, ORANGE)
    svg.circle(hi_x, range_y, 7, ORANGE)
    svg.text((lo_x + hi_x) / 2, range_y - 14, "6.19–10.56", "value", "middle")
    return svg.finish(
        "docs/research/qos-aqm-lab-notes.md §§37–38",
        "Shaper rates and payload throughput are different measurements; the range shows why 69.5 Mbit/s was not real capacity.",
    )


def radio_rssi() -> str:
    svg = SVG(
        "Measured signal change after EEPROM calibration",
        "Fixed-position before/after comparisons; farther right is stronger signal.",
        590,
    )
    svg.panel(35, 92, 930, 410, "Received signal strength (dBm)")
    left, right = 230, 925
    min_dbm, max_dbm = -70, -15
    for tick in range(-70, -14, 5):
        x = left + (right - left) * (tick - min_dbm) / (max_dbm - min_dbm)
        svg.line(x, 150, x, 425, "grid")
        svg.text(x, 452, tick, "small", "middle")
    rows = [
        ("5 GHz · S23 far", -65.0, -61.0, "+4.0 dB"),
        ("5 GHz · Pi near", -26.0, -21.0, "+5.0 dB"),
        ("2.4 GHz · Pi near", -22.8, -20.6, "+2.2 dB"),
    ]
    for i, (label, before, after, delta) in enumerate(rows):
        y = 195 + i * 92
        bx = left + (right - left) * (before - min_dbm) / (max_dbm - min_dbm)
        ax = left + (right - left) * (after - min_dbm) / (max_dbm - min_dbm)
        svg.text(left - 15, y + 5, label, "label", "end")
        svg.line(bx, y, ax, y, "axis", stroke_width=5, stroke=TEAL)
        svg.circle(bx, y, 9, BLUE)
        svg.circle(ax, y, 9, TEAL)
        svg.text(bx, y - 18, f"{before:g}", "small", "middle")
        svg.text(ax, y + 25, f"{after:g}", "small", "middle")
        svg.text(ax + 20, y + 5, delta, "value")
    svg.circle(390, 480, 6, BLUE)
    svg.text(403, 484, "stock / stock-emulation", "small")
    svg.circle(600, 480, 6, TEAL)
    svg.text(613, 484, "30 dBm profile", "small")
    return svg.finish(
        "docs/research/eeprom-calibration.md",
        "2.4 GHz far-field result was inconclusive and is deliberately excluded; near-field rows use 15 samples each.",
    )


CHARTS = {
    "aqm-latency-throughput.svg": aqm_latency,
    "napi-weight-ab.svg": napi_ab,
    "aqm-grace-tuning.svg": grace_tuning,
    "aqm-hold-ab.svg": hold_ab,
    "autorate-ceiling.svg": autorate_ceiling,
    "radio-rssi.svg": radio_rssi,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated SVGs differ")
    args = parser.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for filename, render in CHARTS.items():
        path = OUT / filename
        content = render()
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(filename)
        else:
            path.write_text(content)
            print(path.relative_to(ROOT))
    if stale:
        print("stale graph(s): " + ", ".join(stale))
        return 1
    if args.check:
        print(f"{len(CHARTS)} measured-claim graphs are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
