#!/bin/sh

. /lib/functions/system.sh

case "$(board_name)" in
linksys,e8450-ubi)
	# HW flow offloading with qos-06 AQM: PPE/QDMA offloads transit flows to
	# hardware queues; the occupancy-driven AQM evicts saturated flows back to
	# CAKE/SQM, delivering near-CAKE latency at lower CPU cost.
	uci -q set firewall.@defaults[0].flow_offloading='1'
	uci -q set firewall.@defaults[0].flow_offloading_hw='1'
	uci -q commit firewall
	;;
esac

exit 0
