#!/bin/sh

. /lib/functions/system.sh

case "$(board_name)" in
linksys,e8450-ubi)
	# PPE/QDMA hardware offloading carries established transit flows. Native
	# per-port queueing caps WAN egress; CAKE owns non-offloaded traffic.
	uci -q set firewall.@defaults[0].flow_offloading='1'
	uci -q set firewall.@defaults[0].flow_offloading_hw='1'
	uci -q commit firewall
	;;
esac

exit 0
