#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=4

PROG=/usr/sbin/sqm-autorate-rust

start_service() {
	[ -x "$PROG" ] || return 0
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param file /etc/config/sqm-autorate
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
